### ISSUE TITLE
thank you, but iOS doesn't work

### ISSUE THREAD

**Issue by jeffreyliu8** [md-weber/webrtc_tutorial#1]
if you create a room with iOS , it would crash right away.

**Comment by VladimirTambovtsev** [comment]
any updates? I'm really interesting in it

**Comment by waqadArshad** [comment]
@md-weber any update on this?

**Comment by md-weber** [comment]
I created a branch and there it works on a real device. The simulator is unfortunately not able to execute the Video stream.
https://github.com/flutter-webrtc/flutter-webrtc/issues/558

I need to double check if it also accepts receiving calls, but for now it looks quite promising.
https://github.com/md-weber/webrtc_tutorial/tree/1-ios-does-not-work
