### ISSUE TITLE
only working on one computer

### ISSUE THREAD

**Issue by iwalpola** [md-weber/webrtc_tutorial#3]
Hi, thanks for the great tutorial!

I'm having an issue where I cannot establish a p2p call between 2 computers, but its working fine when testing two browsers on the same computer.

Is this a known issue?

**Comment by iwalpola** [comment]
my mistake, I tried again now and it works fine. I think it took tome for hosting to get set up.

**Comment by md-weber** [comment]
Glad to hear that :)
