### ISSUE TITLE
microphone not working. cannot communicate with voice.

### ISSUE THREAD

**Issue by HamzaMuazzam** [md-weber/webrtc_tutorial#6]
microphone not working. cannot communicate with voice.

**Comment by mtri-git** [comment]
> microphone not working. cannot communicate with voice.

In `.getUserMedia({'video': true, 'audio': false}); ` you can change to `.getUserMedia({'video': true, 'audio': true});`

**Comment by md-weber** [comment]
Because it is only a setting in the UserMedia I think this is not a bug just a feature of WebRTC itself. Therefore I will close the bug. Thanks @mtri-git for your comment.
