### ISSUE TITLE
Android app crashes if I use navigator.mediaDevices.getDisplayMedia to share my screen, but it's works fine in web

### ISSUE THREAD

**Issue by techno123454321** [md-weber/webrtc_tutorial#8]
If I use navigator.mediaDevices.getDisplayMedia to share my screen with others then my android apps crash with an error:

"java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION"

But it works fine in web, do you have an idea why ???

**Comment by md-weber** [comment]
Yes that is a issue of permissions, if you check the Android Manifest you will see there are the following permissions added with the last PR https://github.com/md-weber/webrtc_tutorial/pull/9.

```
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
```

This should make the error go away, feel free to double check 👍
